spring:
  application:
    name: apigw

  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/v3/api-docs, /api/v1/users/**
        - id: post
          uri: lb://POST-SERVICE
          predicates:
            - Path=/posts/v3/api-docs, /api/v1/posts/**, /api/v1/comments/**, /api/v1/tags/**, /api/v1/categories/**
        - id: auth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/v3/api-docs, /api/v1/auth/**
        - id: notification
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/v3/api-docs, /api/v1/notifications/**
        - id: admin
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/v3/api-docs, /api/v1/admin/**
      ##允许请求跨域
      globalcors:
        add-to-simple-url-handler-mapping: true # 允许Options请求询问是否允许跨域
        cors-configurations:
          "[/**]":
            allowedOrigins:
              - "http://USER-SERVICE:8000"
              - "http://POST-SERVICE:7000"
              - "http://ADMIN-SERVICE:8500"
              - "http://NOTIFICATION-SERVICE:6000"
              - "http://AUTH-SERVICE:9000"
              - "http://localhost:5173"
              - "http://localhost:5174"
              - "http://localhost:80"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "PATCH"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true # 允许cookie
            maxAge: 360000

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      #        primaryName: API Gateway Service
      - url: /users/v3/api-docs
        name: User Service
      #        primaryName: User Service
      - url: /posts/v3/api-docs
        name: Post Service
      #        primaryName: Post Service
      - url: /auth/v3/api-docs
        name: Auth Service
      #        primaryName: Auth Service
      - url: /notifications/v3/api-docs
        name: Notification Service
      # primaryName: Auth Service
      - url: /admin/v3/api-docs
        name: Admin Service
#        primaryName: Auth Service

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

logging:
  level:
    root: debug
  pattern:
    level: "trace_id=%mdc{traceId} span_id=%mdc{spanId} trace_flags=%mdc{traceFlags} %p"
