spring:
  config:
    import: optional:classpath:.env[.yml]
#    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: itireland
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  rabbitmq:
    addresses: localhost:5672

  mail:
    host: smtp.gmail.com
    username: yp1990@gmail.com
    password: ${EMAIL_PASS}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8082

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "trace_id=%mdc{traceId} span_id=%mdc{spanId} trace_flags=%mdc{traceFlags} %p"


itireland:
  openapi:
    dev-url: http://localhost:8082
    prod-url: https://itireland.herokuapp.com


rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key