server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/post

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "trace_id=%mdc{traceId} span_id=%mdc{spanId} trace_flags=%mdc{traceFlags} %p"

openapi:
  service:
    title: post-service doc #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://localhost:8080 #api gateway url

springdoc:
  api-docs:
    path: /posts/v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    path: /posts/swagger-ui.html

itireland:
  openapi:
    dev-url: http://localhost:8081
    prod-url: https://itireland.herokuapp.com